### PR TITLE
Adding Blocks and Connectors removing Actions and Rules

### PR DESCRIPTION
**Pull request by til0n**
This is my current understanding of the new concepts.
Please review and let me know if there are things we should change.

### CODE REVIEW

**Comment by yotamhc** [comment]
I would prefer immutable objects, any reason not to have that?

**Comment by til0n** [comment]
The connector class is immutable.
Having them immutable means having an interface with a builder class for each such class - right?
How does the builder pattern looks with inheritance?

**Comment by yotamhc** [comment]
It is up to you whether a builder also inherits from the parent's builder. Usually it does, but it is not necessary.

**Comment by til0n** [comment]
OK, I will try to change it.

**Comment by til0n** [comment]
I'm trying to change the classes to use the builder pattern but since they are abstract it is not clear to me how this should be done.
https://weblogs.java.net/blog/emcmanus/archive/2010/10/25/using-builder-pattern-subclasses
I have looked at the above link, but it seems real cumbersome.
Am I missing anything?
I couldn't find any examples in the current controller code.

**Comment by yotamhc** [comment]
I am not sure why you need the Init class and in general why it became so complicated. I am merging and will try to make it simpler on my side.

**Comment by til0n** [comment]
This article explains it pretty well.

https://weblogs.java.net/blog/emcmanus/archive/2010/10/25/using-builder-pattern-subclasses

**Pull request merged**
